# Generated by Django 4.1.7 on 2023-04-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_alter_post_edited'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
